### PR TITLE
Add SonicPiSendSelection and SonicPiSendLine

### PR DESCRIPTION
**Pull request by R-Bas**
New features:

- Send last selection with `<leader>e`  (#21)

- Send current line with  `<leader>E`

### CODE REVIEW

**Comment by dermusikman** [comment]
Thanks so much for doing this work! As I test SonicPiSendSelection, it feels a little counter-intuitive: I enter visual mode, make a selection, exit visual mode, and then use the feature... I wonder if it makes sense to make this feature a visual-mode command? How do you typically use it, @R-Bas?

**Comment by lilyinstarlight** [comment]
Hi @R-Bas and @dermusikman! I figured I would chime in here real quick that supporting visual-mode ranges in `SonicPiSendBuffer` can be done without much modification (and it would work in normal mode and visual mode, only sending the lines from the selection when running the mapping from visual mode). Feel free to adapt the change from this commit (in my fork) if you'd like to add that behavior: lilyinstarlight/vim-sonic-pi@d39d286

**Comment by dermusikman** [comment]
Hi @lilyinstarlight - that feels a lot more intuitive for selections, thank you! I'd be happy to make those changes, crediting you; but I invite you to submit a PR, if you'd like?

**Comment by lilyinstarlight** [comment]
I didn't want to take the PR away from @R-Bas. However, if you are interested in any of my changes or additions in the fork (including getting the script in the auto-update branch working), I'm happy to PR as much or as little as you'd like. If you are still maintaining this plugin (it seems I mistakenly assumed you'd moved on when I forked it a few months ago), I'd love to collaborate on it! There's no need to duplicate work if this repo is still alive

**Comment by R-Bas** [comment]
It is indeed a bit counter-intuitive, i made it this way because i'm not a Vim expert and didn't know how to do it another way.
I can't test it now, but @lilyinstarlight solution seems of course way better.
Feel free to make changes to this PR or delete it, as you want.

**Comment by dermusikman** [comment]
Thank you both! I certainly haven't been active on this plugin for a long time, but I haven't wanted to abandon it entirely, either. I don't foresee myself adding major features, but I am happy to accept PRs for updates from the community :)

It looks like your fork, @lilyinstarlight, is a pretty clear upgrade! I'd love to backport that selection feature, and would prefer to give you the author credit in a PR if it's not too inconvenient. That's a feature I should've added from the beginning but simply didn't take the time to figure out.

And thanks, @R-Bas - after getting @lilyinstarlight's update added, I'll experiment with SonicPiSendLine() to see if it still adds things. Thanks for the PR and for sharing that feature!

I'll make a point to update the README, too, to reflect the status of this project. I am really grateful that people are using this plugin and building from it, and want to be sure that new users are aware of more active forks like @lilyinstarlight's, too

Thanks again!

**Comment by lilyinstarlight** [comment]
> It looks like your fork, @lilyinstarlight, is a pretty clear upgrade! I'd love to backport that selection feature, and would prefer to give you the author credit in a PR if it's not too inconvenient. That's a feature I should've added from the beginning but simply didn't take the time to figure out.

I'll make a PR later tonight (US eastern time zone) if I get a chance with a change roughly equivalent to that commit linked earlier (minus the first `vnoremap` which is specific to the built-in Sonic Pi log buffer in my fork)

> I'll make a point to update the README, too, to reflect the status of this project. I am really grateful that people are using this plugin and building from it, and want to be sure that new users are aware of more active forks like @lilyinstarlight's, too

I appreciate the kind words about my fork! I had one more thing on my list<sup>1</sup> before I was planning to more actively share it but you are welcome to link it from the readme now (if I understood your intent with that last sentence correctly) since it already works well and I use it myself as my primary Sonic Pi interface.

<sup>1: I wanted to add some reasonable default logic to deal with when to automatically show the log buffer since it won't work if the Sonic Pi GUI is already up because the UDP OSC port would already be listening</sup>

 I greatly appreciate your work on this plugin!

**Comment by R-Bas** [comment]
Just tested the merged changes from #25 and it works great !

> I'll experiment with SonicPiSendLine() to see if it still adds things

@dermusikman I personally don't think that adding a new command for just one line makes sense anymore as you can now quickly do it with `<shift + v> <leader>r` .

**Comment by dermusikman** [comment]
Thanks @R-Bas!

**Pull request closed without merging**
